"""add reference_number

Revision ID: 5e72e740dd7a
Revises: c0ee3d80e917
Create Date: 2026-01-22 04:27:23.779635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e72e740dd7a'
down_revision: Union[str, Sequence[str], None] = 'c0ee3d80e917'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('reference_number', sa.String(), nullable=True))
    op.add_column('invoices', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('line_items', sa.Column('account_guess', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('line_items', 'account_guess')
    op.drop_column('invoices', 'notes')
    op.drop_column('invoices', 'reference_number')
    # ### end Alembic commands ###
