"""add reference_number notes and account_guess

Revision ID: 931beeb09c27
Revises: c0ee3d80e917
Create Date: 2025-12-31 01:31:03.556670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '931beeb09c27'
down_revision: Union[str, Sequence[str], None] = 'c0ee3d80e917'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
