"""Add VAT compliance fields

Revision ID: add_vat_compliance_fields
Revises: add_reference_number_to_invoices
Create Date: 2025-01-22 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_vat_compliance_fields'
down_revision: Union[str, Sequence[str], None] = '5e72e740dd7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add VAT compliance fields to invoices table
    op.add_column('invoices', sa.Column('tax_percentage', sa.Float(), nullable=True))
    op.add_column('invoices', sa.Column('is_reverse_charge', sa.Boolean(), nullable=True, default=False))
    op.add_column('invoices', sa.Column('supplier_trn', sa.String(), nullable=True))
    op.add_column('invoices', sa.Column('supplier_address', sa.String(), nullable=True))
    op.add_column('invoices', sa.Column('customer_trn', sa.String(), nullable=True))
    op.add_column('invoices', sa.Column('customer_address', sa.String(), nullable=True))
    op.add_column('invoices', sa.Column('date_of_supply', sa.Date(), nullable=True))
    op.add_column('invoices', sa.Column('currency_rate', sa.Float(), nullable=True, default=1.0))
    
    # Add tax fields to line_items table
    op.add_column('line_items', sa.Column('tax_rate', sa.Float(), nullable=True))
    op.add_column('line_items', sa.Column('tax_amount', sa.Float(), nullable=True))
    op.add_column('line_items', sa.Column('is_reverse_charge', sa.Boolean(), nullable=True, default=False))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('line_items', 'is_reverse_charge')
    op.drop_column('line_items', 'tax_amount')
    op.drop_column('line_items', 'tax_rate')
    op.drop_column('invoices', 'currency_rate')
    op.drop_column('invoices', 'date_of_supply')
    op.drop_column('invoices', 'customer_address')
    op.drop_column('invoices', 'customer_trn')
    op.drop_column('invoices', 'supplier_address')
    op.drop_column('invoices', 'supplier_trn')
    op.drop_column('invoices', 'is_reverse_charge')
    op.drop_column('invoices', 'tax_percentage')
    # ### end Alembic commands ###
